Project setup

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -10,7 +10,7 @@ on:
       - main
 
 jobs:
-  ci:
+  workflow:
     runs-on: ubuntu-latest
 
     steps:
@@ -31,19 +31,22 @@ jobs:
         id: strict_lint
         run: npm run lint
 
-      # Fallback/global lint if strict lint fails
-      - name: Run global lint (fallback)
+      # Fallback lint if strict lint fails
+      - name: Run global lint
         if: failure()
         run: |
           echo "Strict lint failed. Running global lint..."
           npm run lint -- --fix
+
+      - name: Force CI failure (test)
+        run: exit 1
 
       # ---------- BUILD ----------
       - name: Build project
         run: npm run build
 
   notify-on-failure:
-    needs: ci
+    needs: workflow
     if: failure() && github.ref == 'refs/heads/main'
     runs-on: ubuntu-latest
 
@@ -55,14 +58,15 @@ jobs:
           server_port: 587
           username: ${{ secrets.SMTP_USERNAME }}
           password: ${{ secrets.SMTP_PASSWORD }}
-          subject: "CI Failed on main branch"
+          subject: "Workflow failed on main branch"
           body: |
-            CI pipeline failed on the main branch.
+            Workflow CI pipeline failed on the main branch.
             Deployment to Vercel was blocked.
 
             Repository: ${{ github.repository }}
             Commit: ${{ github.sha }}
+            Triggered by: ${{ github.actor }}
             Workflow: ${{ github.workflow }}
 
           to: purva.khandeparkar@gmail.com
-          from: CI Notifier purva-khandeparkar
+          from: Workflow Notifier purva-khandeparkar
